name: Build
on:
  push:
    branches:
      - ci-test
jobs:
  publish:
    name: Building ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [linux, macos, windows]
        include:
          - build_target: linux
            os: ubuntu-latest
          - build_target: macos
            os: macos-latest
          - build_target: windows
            os: windows-latest

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
          profile: minimal
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libxkbcommon-dev lld
      - uses: actions/checkout@v2
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: target/release/uad_gui*
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: target/release/uad_gui*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}