name: Build
on:
  push:
    branches:
      - ci-test
jobs:
  uad_windows:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build uad-windows
      run: |
        cargo build --features glow --release
        mv target/release/uad_gui.exe target/release/uad_gui-opengl.exe
        cargo build --release
    - name: Create Vulkan build artifact
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-windows
        path: target/release/uad_gui.exe
    - name: Create OpenGL build artifact
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-opengl-windows
        path: target/release/uad_gui-opengl.exe

  uad_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev lld

    - name: Build uad-linux
      run: |
        cargo build --features glow --release
        mv target/release/uad_gui target/release/uad_gui-opengl
        cargo build --release
     - name: Create Vulkan build artifact
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-linux
        path: target/release/uad_gui

    - name: Create OpenGL build artifact
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-opengl-linux
        path: target/release/uad_gui-opengl

  uad_macos:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build uad-macos
      run: |
        cargo build --features glow --release
        mv target/release/uad_gui target/release/uad_gui-opengl
        cargo build --release
    - name: Create Vulkan build artifact
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-macos
        path: target/release/uad_gui

    - name: Create OpenGL build artifact
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-opengl-macos
        path: target/release/uad_gui-opengl