name: Build
on:
  push:
    branches:
      - ci-test
jobs:
  uad_windows:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build uad-windows
      run: cargo build --release
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-x86_64
        path: target/release/uad_gui.exe

  uad_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev lld
    - name: Build uad-linux
      run: cargo build --release
    - name: Make it executable
      run: chmod +x target/release/uad_gui
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-x86_64-linux
        path: target/release/uad_gui

  uad_macos:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
          rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build uad-macos
      run: cargo build --release
    - name: Make it executable
      run: chmod +x target/release/uad_gui
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: uad_gui-macos
        path: target/release/uad_gui
